arch:
  - amd64
  - ppc64le
sudo: false
language: node_js
node_js:
  - "12"
  - "13"
  - "14"
  - "15"

before_install:
  - travis_retry npm install -g npm@2.14.5
  - travis_retry npm install

script:
  - npm test
